name: ci-merge-main

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - 'src/app/**'
      - '**/Dockerfile*'
      - '!**'

jobs:
  test:
    runs-on: 'ubuntu-latest'
    name: test
    steps:
    - name: test
      uses: actions/checkout@v2
